[package]
name = "json"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "json"
path="src/json.rs"
crate-type = ["lib"]

[profile.dev]
opt-level = 3